server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true