server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/microservice
        refreshInterval: 3s  # Set the refresh interval to 30 seconds
  profiles:
    active: native
management:
  endpoints:
    web:
      exposure:
        include: "*"